import { model } from "./gemini";
import { UI_ARCHITECT_PROMPT } from "../prompts/uiArchitectPrompt";
import { UISchema } from "../types/schema";

export async function generateUISchema(topic: string, wikipediaContent: string, imageUrl?: string, lens?: string): Promise<UISchema> {
  const prompt = `
${UI_ARCHITECT_PROMPT}

Topic: ${topic}
${imageUrl ? `Main Image URL: ${imageUrl}\n(Use this URL in the 'hero' component's 'imageUrl' field)` : ""}
${lens ? `EDUCATIONAL LENS: ${lens}\n(Tailor all content, complexity, and component selection to this lens)` : ""}

Wikipedia Content:
${wikipediaContent.substring(0, 50000)} // Increased limit for larger context window
`;

  const result = await model.generateContent(prompt);
  const response = result.response;
  const text = response.text();
  
  try {
    const schema = JSON.parse(text) as UISchema;
    return schema;
  } catch (error) {
    console.error("Failed to parse Gemini response:", text);
    throw new Error("Invalid UI schema generated by AI");
  }
}
